//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Rents = new HashSet<Rents>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CarModelsID { get; set; }
        public Nullable<int> BrandsID { get; set; }
        public string Number { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> FuelTypeID { get; set; }
        public Nullable<int> TransmissionID { get; set; }
        public Nullable<int> HorsePower { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual CarModels CarModels { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual Transmission1 Transmission1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rents> Rents { get; set; }
    }
}
