//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int ID { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<int> CustomersID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<System.DateTime> HandOverDate { get; set; }
        public Nullable<System.DateTime> TakeOverDate { get; set; }
        public Nullable<System.DateTime> DelayDate { get; set; }
        public Nullable<int> DelayedFine { get; set; }
        public Nullable<decimal> DailyPrice { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Users Users { get; set; }
    }
}
