// <auto-generated />
namespace Online13.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addNewTAble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNewTAble));
        
        string IMigrationMetadata.Id
        {
            get { return "202007050710404_addNewTAble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
